export enum ExamDifficulty {
  EASY = 'Cơ bản',
  MEDIUM = 'Khá',
  HARD = 'Nâng cao'
}

export interface ExamConfig {
  topic: string;
  grade: string;
  difficulty: ExamDifficulty;
  numMultipleChoice: number;
  numEssay: number;
  useTikz: boolean; // true = Generate TikZ, false = Use \includegraphics placeholder
  varyData: boolean; // true = Change numbers, false = Keep exact numbers from source
  language: 'vi' | 'en'; // Added language support
}

export interface GenerationState {
  isLoading: boolean;
  result: string | null;
  error: string | null;
}

// Function to generate template based on language
export const getLatexTemplate = (lang: 'vi' | 'en') => {
  const isVi = lang === 'vi';
  
  return `\\documentclass[a4paper]{article}
\\usepackage[fontsize=13pt]{scrextend} % Size 13pt
\\usepackage[utf8]{inputenc}
\\usepackage[T5]{fontenc} 
\\usepackage[vietnamese]{babel} % Luôn dùng tiếng Việt để hỗ trợ tên riêng và header
\\usepackage{geometry}
\\usepackage{amsmath, amssymb}
\\usepackage{mathptmx} 
\\usepackage{tikz}
\\usepackage{pgfplots}
\\pgfplotsset{compat=1.18}
\\usepackage{enumitem}
\\usepackage{fancyhdr}
\\usepackage{tabularx}
\\usepackage{tasks}
\\usepackage{background}
\\usepackage{xcolor}
\\usepackage{setspace}
\\usepackage{tcolorbox}
\\usepackage{graphicx}

% --- COLORS ---
\\definecolor{cambridgeblue}{RGB}{163, 193, 173}
\\definecolor{maincolor}{RGB}{0, 51, 102}

% --- WATERMARK ---
\\backgroundsetup{
    scale=5,
    color=cambridgeblue,
    opacity=0.2,
    angle=45,
    contents={\\textbf{Trần Công Nghĩa}}
}

% --- PAGE CONFIG ---
\\geometry{top=2cm, bottom=2cm, left=2cm, right=2cm}
\\usetikzlibrary{shapes.geometric, patterns, positioning, calc, intersections, decorations.text, quotes, angles} 

% --- HEADER/FOOTER ---
\\pagestyle{fancy}
\\fancyhf{}
\\lhead{\\textbf{${isVi ? 'Toán Cambridge Lớp [LỚP]' : 'Cambridge Math Grade [GRADE]'}}}
\\rhead{\\textcolor{maincolor}{\\textbf{${isVi ? 'Chủ đề: [CHỦ ĐỀ]' : 'Topic: [TOPIC]'}}}} 
\\rfoot{${isVi ? 'Trang \\thepage' : 'Page \\thepage'}}
\\lfoot{\\textcolor{maincolor}{\\textbf{${isVi ? 'SĐT/Zalo: 0866611402 (Trần Nghĩa)' : 'Contact: 0866611402 (Tran Nghia)'}}}}

\\renewcommand{\\headrulewidth}{0.5pt}

% --- TASKS CONFIG ---
\\settasks{
    label=\\textbf{\\Alph*.},
    label-width=1.5em,
    item-indent=1.5em,
    column-sep=1em,
    after-item-skip=2pt
}

% --- QUESTION BOX ---
\\newenvironment{questionbox}[1]
    {\\par\\medskip\\noindent\\textbf{#1} \\ignorespaces} 
    {\\par\\vspace{0.5em}}

\\begin{document}
\\onehalfspacing

% ================= HEADER BLOCK =================
\\noindent
\\begin{tabularx}{\\linewidth}{@{}l X r@{}}
    \\textbf{${isVi ? 'TRƯỜNG: ...........................................' : 'SCHOOL: ...........................................'}} & & \\textbf{${isVi ? 'ĐỀ KIỂM TRA 1 TIẾT' : 'MID-TERM TEST'}} \\\\
    \\textbf{${isVi ? 'HỌ VÀ TÊN: .......................................' : 'FULL NAME: .......................................'}} & & \\textit{${isVi ? 'Môn: Toán' : 'Subject: Mathematics'}} \\\\
    \\textbf{${isVi ? 'LỚP: ...................................................' : 'CLASS: ...................................................'}} & & \\textit{${isVi ? 'Thời gian: 45 phút' : 'Time: 45 minutes'}}
\\end{tabularx}

\\vspace{0.5cm}
\\begin{center}
    \\textbf{\\Large ${isVi ? 'CHỦ ĐỀ: [CHỦ ĐỀ IN HOA]' : 'TOPIC: [TOPIC UPPERCASE]'}} \\\\ 
    \\textit{(${isVi ? 'Không sử dụng tài liệu trong giờ làm bài' : 'No materials allowed during the test'})}
\\end{center}
\\noindent\\rule{\\linewidth}{1pt} 
\\vspace{0.5cm}
% ================================================

\\section*{${isVi ? 'PHẦN I: TRẮC NGHIỆM ([SỐ LƯỢNG TN] câu)' : 'PART I: MULTIPLE CHOICE ([NUM_MC] questions)'}}

% [CONTENT GENERATED BY AI WILL GO HERE]

\\section*{${isVi ? 'PHẦN II: TỰ LUẬN ([SỐ LƯỢNG TL] câu)' : 'PART II: CONSTRUCTED RESPONSE ([NUM_ESSAY] questions)'}}

% [CONTENT GENERATED BY AI WILL GO HERE]

\\end{document}`;
};